"""
Dublin Core Metadata Element Set (DCMES) — ISO 15836-1:2017
and Dublin Core Metadata Terms (DCTERMS) — ISO 15836-2:2019

The Dublin Core Metadata Initiative (DCMI) defines two sets of metadata elements:
1. The 15 classic "Dublin Core" elements (dc:) — simple, widely interoperable
2. The extended DCMI Metadata Terms (dcterms:) — more precise semantics

References:
  ISO 15836-1:2017 — Dublin Core Metadata Element Set
  ISO 15836-2:2019 — DCMI Metadata Terms
  https://www.dublincore.org/specifications/dublin-core/
"""
from typing import Any, Dict
from standards.base import (
    FieldDefinition, MetadataStandard,
    Obligation, Cardinality, RepresentationTerm
)

NS_DC = "http://purl.org/dc/elements/1.1/"
NS_DCT = "http://purl.org/dc/terms/"


# ── Classic 15 Dublin Core elements ────────────────────────────────────────
FIELDS_DC: Dict[str, FieldDefinition] = {
    "title": FieldDefinition(
        name="title",
        description="A name given to the resource.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.TEXT,
        values="Free text",
        reference="ISO 15836-1:2017 §6.1 / DCMI dc:title",
        layer="Core",
        group="",
        xml_element="dc:title",
        namespace=NS_DC,
    ),
    "creator": FieldDefinition(
        name="creator",
        description=(
            "An entity primarily responsible for making the resource. "
            "Examples: a person, organisation, or service."
        ),
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.NAME,
        values="Free text agent name or URI",
        reference="ISO 15836-1:2017 §6.2 / DCMI dc:creator",
        layer="Core",
        group="",
        xml_element="dc:creator",
        namespace=NS_DC,
    ),
    "subject": FieldDefinition(
        name="subject",
        description="The topic of the resource. Typically keywords, key phrases, or classification codes.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.TEXT,
        values="Free text; controlled vocabulary term; classification code",
        reference="ISO 15836-1:2017 §6.3 / DCMI dc:subject",
        layer="Core",
        group="",
        xml_element="dc:subject",
        namespace=NS_DC,
    ),
    "description": FieldDefinition(
        name="description",
        description="An account of the resource including abstract, table of contents, or free-text.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.TEXT,
        values="Free text",
        reference="ISO 15836-1:2017 §6.4 / DCMI dc:description",
        layer="Core",
        group="",
        xml_element="dc:description",
        namespace=NS_DC,
    ),
    "publisher": FieldDefinition(
        name="publisher",
        description="An entity responsible for making the resource available.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.NAME,
        values="Free text agent name or URI",
        reference="ISO 15836-1:2017 §6.5 / DCMI dc:publisher",
        layer="Core",
        group="",
        xml_element="dc:publisher",
        namespace=NS_DC,
    ),
    "contributor": FieldDefinition(
        name="contributor",
        description="An entity responsible for making contributions to the resource.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.NAME,
        values="Free text agent name or URI",
        reference="ISO 15836-1:2017 §6.6 / DCMI dc:contributor",
        layer="Core",
        group="",
        xml_element="dc:contributor",
        namespace=NS_DC,
    ),
    "date": FieldDefinition(
        name="date",
        description="A point or period of time associated with an event in the lifecycle of the resource.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.DATETIME,
        values="ISO 8601 date or datetime",
        reference="ISO 15836-1:2017 §6.7 / DCMI dc:date",
        layer="Core",
        group="",
        xml_element="dc:date",
        namespace=NS_DC,
    ),
    "type": FieldDefinition(
        name="type",
        description="The nature or genre of the resource. Use DCMI Type Vocabulary.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.CODE,
        values=(
            "Collection | Dataset | Event | Image | InteractiveResource | "
            "MovingImage | PhysicalObject | Service | Software | Sound | "
            "StillImage | Text"
        ),
        reference="ISO 15836-1:2017 §6.8 / DCMI dc:type",
        layer="Core",
        group="",
        xml_element="dc:type",
        namespace=NS_DC,
    ),
    "format": FieldDefinition(
        name="format",
        description="The file format, physical medium, or dimensions of the resource.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.CODE,
        values="IANA MIME type or free text, e.g., application/pdf",
        reference="ISO 15836-1:2017 §6.9 / DCMI dc:format",
        layer="Core",
        group="",
        xml_element="dc:format",
        namespace=NS_DC,
    ),
    "identifier": FieldDefinition(
        name="identifier",
        description="An unambiguous reference to the resource within a given context.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.IDENTIFIER,
        values="URI, DOI, ISBN, ISSN, or other formal identifier scheme",
        reference="ISO 15836-1:2017 §6.10 / DCMI dc:identifier",
        layer="Core",
        group="",
        xml_element="dc:identifier",
        namespace=NS_DC,
    ),
    "source": FieldDefinition(
        name="source",
        description="A related resource from which the described resource is derived.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.TEXT,
        values="URI or descriptive string",
        reference="ISO 15836-1:2017 §6.11 / DCMI dc:source",
        layer="Core",
        group="",
        xml_element="dc:source",
        namespace=NS_DC,
    ),
    "language": FieldDefinition(
        name="language",
        description="A language of the resource. Use RFC 5646 / BCP 47 or ISO 639.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.CODE,
        values="BCP 47 tag (e.g., en, fr, de) or ISO 639-2/3 (e.g., eng, fra)",
        reference="ISO 15836-1:2017 §6.12 / DCMI dc:language",
        layer="Core",
        group="",
        xml_element="dc:language",
        namespace=NS_DC,
    ),
    "relation": FieldDefinition(
        name="relation",
        description="A related resource.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.IDENTIFIER,
        values="URI of the related resource",
        reference="ISO 15836-1:2017 §6.13 / DCMI dc:relation",
        layer="Core",
        group="",
        xml_element="dc:relation",
        namespace=NS_DC,
    ),
    "coverage": FieldDefinition(
        name="coverage",
        description="The spatial or temporal topic of the resource, or the jurisdiction under which the resource is relevant.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.TEXT,
        values="Place name, time period, or jurisdiction",
        reference="ISO 15836-1:2017 §6.14 / DCMI dc:coverage",
        layer="Core",
        group="",
        xml_element="dc:coverage",
        namespace=NS_DC,
    ),
    "rights": FieldDefinition(
        name="rights",
        description="Information about rights held in and over the resource.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.TEXT,
        values="Rights statement URI or free text",
        reference="ISO 15836-1:2017 §6.15 / DCMI dc:rights",
        layer="Core",
        group="",
        xml_element="dc:rights",
        namespace=NS_DC,
    ),
}

# ── DCTERMS extensions ──────────────────────────────────────────────────────
FIELDS_DCT_EXTRA: Dict[str, FieldDefinition] = {
    "abstract": FieldDefinition(
        name="abstract",
        description="A summary of the resource.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.TEXT,
        values="Free text",
        reference="ISO 15836-2:2019 / DCMI dcterms:abstract",
        layer="Terms",
        group="",
        xml_element="dcterms:abstract",
        namespace=NS_DCT,
    ),
    "accessRights": FieldDefinition(
        name="accessRights",
        description="Information about who can access the resource or an indication of its security status.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.TEXT,
        values="Free text or URI to rights statement",
        reference="ISO 15836-2:2019 / DCMI dcterms:accessRights",
        layer="Terms",
        group="",
        xml_element="dcterms:accessRights",
        namespace=NS_DCT,
    ),
    "accrualMethod": FieldDefinition(
        name="accrualMethod",
        description="The method by which items are added to a collection.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.TEXT,
        values="DCMI Collection Description Accrual Method vocabulary",
        reference="ISO 15836-2:2019 / DCMI dcterms:accrualMethod",
        layer="Terms",
        group="",
        xml_element="dcterms:accrualMethod",
        namespace=NS_DCT,
    ),
    "accrualPeriodicity": FieldDefinition(
        name="accrualPeriodicity",
        description="The frequency with which items are added to a collection.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.TEXT,
        values="DCMI Frequency vocabulary (annual, monthly, daily, etc.)",
        reference="ISO 15836-2:2019 / DCMI dcterms:accrualPeriodicity",
        layer="Terms",
        group="",
        xml_element="dcterms:accrualPeriodicity",
        namespace=NS_DCT,
    ),
    "alternative": FieldDefinition(
        name="alternative",
        description="An alternative name for the resource.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.TEXT,
        values="Free text",
        reference="ISO 15836-2:2019 / DCMI dcterms:alternative",
        layer="Terms",
        group="",
        xml_element="dcterms:alternative",
        namespace=NS_DCT,
    ),
    "audience": FieldDefinition(
        name="audience",
        description="A class of entity for whom the resource is intended or useful.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.TEXT,
        values="Free text or URI",
        reference="ISO 15836-2:2019 / DCMI dcterms:audience",
        layer="Terms",
        group="",
        xml_element="dcterms:audience",
        namespace=NS_DCT,
    ),
    "available": FieldDefinition(
        name="available",
        description="Date that the resource became or will become available.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.DATETIME,
        values="ISO 8601 date",
        reference="ISO 15836-2:2019 / DCMI dcterms:available",
        layer="Terms",
        group="",
        xml_element="dcterms:available",
        namespace=NS_DCT,
    ),
    "bibliographicCitation": FieldDefinition(
        name="bibliographicCitation",
        description="A bibliographic reference for the resource.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.TEXT,
        values="Formatted citation string",
        reference="ISO 15836-2:2019 / DCMI dcterms:bibliographicCitation",
        layer="Terms",
        group="",
        xml_element="dcterms:bibliographicCitation",
        namespace=NS_DCT,
    ),
    "conformsTo": FieldDefinition(
        name="conformsTo",
        description="An established standard to which the described resource conforms.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.URI,
        values="URI of the standard",
        reference="ISO 15836-2:2019 / DCMI dcterms:conformsTo",
        layer="Terms",
        group="",
        xml_element="dcterms:conformsTo",
        namespace=NS_DCT,
    ),
    "created": FieldDefinition(
        name="created",
        description="Date of creation of the resource.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.DATETIME,
        values="ISO 8601 date",
        reference="ISO 15836-2:2019 / DCMI dcterms:created",
        layer="Terms",
        group="",
        xml_element="dcterms:created",
        namespace=NS_DCT,
    ),
    "dateAccepted": FieldDefinition(
        name="dateAccepted",
        description="Date of acceptance of the resource.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.ONE,
        representation_term=RepresentationTerm.DATETIME,
        values="ISO 8601 date",
        reference="ISO 15836-2:2019 / DCMI dcterms:dateAccepted",
        layer="Terms",
        group="",
        xml_element="dcterms:dateAccepted",
        namespace=NS_DCT,
    ),
    "dateCopyrighted": FieldDefinition(
        name="dateCopyrighted",
        description="Date of copyright.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.ONE,
        representation_term=RepresentationTerm.DATETIME,
        values="ISO 8601 year or date",
        reference="ISO 15836-2:2019 / DCMI dcterms:dateCopyrighted",
        layer="Terms",
        group="",
        xml_element="dcterms:dateCopyrighted",
        namespace=NS_DCT,
    ),
    "dateSubmitted": FieldDefinition(
        name="dateSubmitted",
        description="Date of submission of the resource.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.ONE,
        representation_term=RepresentationTerm.DATETIME,
        values="ISO 8601 date",
        reference="ISO 15836-2:2019 / DCMI dcterms:dateSubmitted",
        layer="Terms",
        group="",
        xml_element="dcterms:dateSubmitted",
        namespace=NS_DCT,
    ),
    "extent": FieldDefinition(
        name="extent",
        description="The size or duration of the resource.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.QUANTITY,
        values="Numeric value with unit",
        reference="ISO 15836-2:2019 / DCMI dcterms:extent",
        layer="Terms",
        group="",
        xml_element="dcterms:extent",
        namespace=NS_DCT,
    ),
    "hasFormat": FieldDefinition(
        name="hasFormat",
        description="A related resource that is substantially the same as the described resource, but in a different format.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.URI,
        values="URI of the related resource",
        reference="ISO 15836-2:2019 / DCMI dcterms:hasFormat",
        layer="Terms",
        group="",
        xml_element="dcterms:hasFormat",
        namespace=NS_DCT,
    ),
    "hasPart": FieldDefinition(
        name="hasPart",
        description="A related resource that is included either physically or logically in the described resource.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.URI,
        values="URI of the part",
        reference="ISO 15836-2:2019 / DCMI dcterms:hasPart",
        layer="Terms",
        group="",
        xml_element="dcterms:hasPart",
        namespace=NS_DCT,
    ),
    "hasVersion": FieldDefinition(
        name="hasVersion",
        description="A related resource that is a version, edition, or adaptation of the described resource.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.URI,
        values="URI of the version",
        reference="ISO 15836-2:2019 / DCMI dcterms:hasVersion",
        layer="Terms",
        group="",
        xml_element="dcterms:hasVersion",
        namespace=NS_DCT,
    ),
    "instructionalMethod": FieldDefinition(
        name="instructionalMethod",
        description="A process, used to engender knowledge, attitudes and skills, that the described resource is designed to support.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.TEXT,
        values="Free text",
        reference="ISO 15836-2:2019 / DCMI dcterms:instructionalMethod",
        layer="Terms",
        group="",
        xml_element="dcterms:instructionalMethod",
        namespace=NS_DCT,
    ),
    "isFormatOf": FieldDefinition(
        name="isFormatOf",
        description="A related resource that is substantially the same as the described resource, but in a different format.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.URI,
        values="URI",
        reference="ISO 15836-2:2019 / DCMI dcterms:isFormatOf",
        layer="Terms",
        group="",
        xml_element="dcterms:isFormatOf",
        namespace=NS_DCT,
    ),
    "isPartOf": FieldDefinition(
        name="isPartOf",
        description="A related resource in which the described resource is physically or logically included.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.URI,
        values="URI",
        reference="ISO 15836-2:2019 / DCMI dcterms:isPartOf",
        layer="Terms",
        group="",
        xml_element="dcterms:isPartOf",
        namespace=NS_DCT,
    ),
    "isReferencedBy": FieldDefinition(
        name="isReferencedBy",
        description="A related resource that references, cites, or otherwise points to the described resource.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.URI,
        values="URI",
        reference="ISO 15836-2:2019 / DCMI dcterms:isReferencedBy",
        layer="Terms",
        group="",
        xml_element="dcterms:isReferencedBy",
        namespace=NS_DCT,
    ),
    "isRequiredBy": FieldDefinition(
        name="isRequiredBy",
        description="A related resource that requires the described resource to support its function.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.URI,
        values="URI",
        reference="ISO 15836-2:2019 / DCMI dcterms:isRequiredBy",
        layer="Terms",
        group="",
        xml_element="dcterms:isRequiredBy",
        namespace=NS_DCT,
    ),
    "isVersionOf": FieldDefinition(
        name="isVersionOf",
        description="A related resource of which the described resource is a version, edition, or adaptation.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.URI,
        values="URI",
        reference="ISO 15836-2:2019 / DCMI dcterms:isVersionOf",
        layer="Terms",
        group="",
        xml_element="dcterms:isVersionOf",
        namespace=NS_DCT,
    ),
    "issued": FieldDefinition(
        name="issued",
        description="Date of formal issuance of the resource.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.ONE,
        representation_term=RepresentationTerm.DATETIME,
        values="ISO 8601 date",
        reference="ISO 15836-2:2019 / DCMI dcterms:issued",
        layer="Terms",
        group="",
        xml_element="dcterms:issued",
        namespace=NS_DCT,
    ),
    "license": FieldDefinition(
        name="license",
        description="A legal document giving official permission to do something with the resource.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.URI,
        values="URI of the license, e.g., https://creativecommons.org/licenses/by/4.0/",
        reference="ISO 15836-2:2019 / DCMI dcterms:license",
        layer="Terms",
        group="",
        xml_element="dcterms:license",
        namespace=NS_DCT,
    ),
    "mediator": FieldDefinition(
        name="mediator",
        description="An entity that mediates access to the resource.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.TEXT,
        values="Free text or URI",
        reference="ISO 15836-2:2019 / DCMI dcterms:mediator",
        layer="Terms",
        group="",
        xml_element="dcterms:mediator",
        namespace=NS_DCT,
    ),
    "medium": FieldDefinition(
        name="medium",
        description="The material or physical carrier of the resource.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.TEXT,
        values="Free text or controlled vocabulary term",
        reference="ISO 15836-2:2019 / DCMI dcterms:medium",
        layer="Terms",
        group="",
        xml_element="dcterms:medium",
        namespace=NS_DCT,
    ),
    "modified": FieldDefinition(
        name="modified",
        description="Date on which the resource was changed.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.DATETIME,
        values="ISO 8601 date",
        reference="ISO 15836-2:2019 / DCMI dcterms:modified",
        layer="Terms",
        group="",
        xml_element="dcterms:modified",
        namespace=NS_DCT,
    ),
    "provenance": FieldDefinition(
        name="provenance",
        description="A statement of any changes in ownership and custody of the resource since its creation.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.TEXT,
        values="Free text",
        reference="ISO 15836-2:2019 / DCMI dcterms:provenance",
        layer="Terms",
        group="",
        xml_element="dcterms:provenance",
        namespace=NS_DCT,
    ),
    "references": FieldDefinition(
        name="references",
        description="A related resource that is referenced, cited, or otherwise pointed to by the described resource.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.URI,
        values="URI",
        reference="ISO 15836-2:2019 / DCMI dcterms:references",
        layer="Terms",
        group="",
        xml_element="dcterms:references",
        namespace=NS_DCT,
    ),
    "replaces": FieldDefinition(
        name="replaces",
        description="A related resource that is supplanted, displaced, or superseded by the described resource.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.URI,
        values="URI",
        reference="ISO 15836-2:2019 / DCMI dcterms:replaces",
        layer="Terms",
        group="",
        xml_element="dcterms:replaces",
        namespace=NS_DCT,
    ),
    "requires": FieldDefinition(
        name="requires",
        description="A related resource that is required by the described resource to support its function.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.URI,
        values="URI",
        reference="ISO 15836-2:2019 / DCMI dcterms:requires",
        layer="Terms",
        group="",
        xml_element="dcterms:requires",
        namespace=NS_DCT,
    ),
    "rightsHolder": FieldDefinition(
        name="rightsHolder",
        description="A person or organisation owning or managing rights over the resource.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.TEXT,
        values="Free text or URI",
        reference="ISO 15836-2:2019 / DCMI dcterms:rightsHolder",
        layer="Terms",
        group="",
        xml_element="dcterms:rightsHolder",
        namespace=NS_DCT,
    ),
    "spatial": FieldDefinition(
        name="spatial",
        description="Spatial characteristics of the resource.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.TEXT,
        values="Free text or controlled vocabulary",
        reference="ISO 15836-2:2019 / DCMI dcterms:spatial",
        layer="Terms",
        group="",
        xml_element="dcterms:spatial",
        namespace=NS_DCT,
    ),
    "tableOfContents": FieldDefinition(
        name="tableOfContents",
        description="A list of subunits of the resource.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.TEXT,
        values="Free text",
        reference="ISO 15836-2:2019 / DCMI dcterms:tableOfContents",
        layer="Terms",
        group="",
        xml_element="dcterms:tableOfContents",
        namespace=NS_DCT,
    ),
    "temporal": FieldDefinition(
        name="temporal",
        description="Temporal characteristics of the resource.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.DATETIME,
        values="ISO 8601 or DCMI Period",
        reference="ISO 15836-2:2019 / DCMI dcterms:temporal",
        layer="Terms",
        group="",
        xml_element="dcterms:temporal",
        namespace=NS_DCT,
    ),
    "valid": FieldDefinition(
        name="valid",
        description="Date (often a range) of validity of a resource.",
        obligation=Obligation.OPTIONAL,
        cardinality=Cardinality.MANY,
        representation_term=RepresentationTerm.DATETIME,
        values="ISO 8601 date or DCMI Period",
        reference="ISO 15836-2:2019 / DCMI dcterms:valid",
        layer="Terms",
        group="",
        xml_element="dcterms:valid",
        namespace=NS_DCT,
    ),
}

ALL_FIELDS = {**FIELDS_DC, **FIELDS_DCT_EXTRA}


class DublinCoreStandard(MetadataStandard):
    """Dublin Core Metadata Element Set + DCMI Terms (ISO 15836)."""

    id = "dublin_core"
    name = "Dublin Core"
    full_name = "Dublin Core Metadata Element Set / DCMI Metadata Terms"
    version = "ISO 15836-1:2017 + ISO 15836-2:2019"
    organization = "Dublin Core Metadata Initiative (DCMI)"
    domain = "EU"
    description = (
        "Dublin Core is the most widely adopted metadata standard in the world. "
        "It defines 15 core elements (dc:) for basic resource description and "
        "an extended set of terms (dcterms:) with more precise semantics. "
        "Dublin Core is ISO-standardised (ISO 15836) and forms the basis for "
        "many other metadata standards including DCAT-AP and INSPIRE."
    )
    reference = "ISO 15836-1:2017 and ISO 15836-2:2019"
    namespace = NS_DC
    fields = ALL_FIELDS

    _dc_elements = list(FIELDS_DC.keys())
    _ns_markers = [NS_DC, NS_DCT, "purl.org/dc", "dublincore", "oai_dc"]

    def detect_score(self, metadata: Dict[str, Any]) -> float:
        meta_lower = {k.lower(): v for k, v in metadata.items()}
        score = 0.0

        ns = str(metadata.get("@namespace", "") or metadata.get("namespace", ""))
        for marker in self._ns_markers:
            if marker in ns:
                score += 0.4
                break

        dc_hits = sum(1 for f in self._dc_elements if f.lower() in meta_lower)
        score += (dc_hits / len(self._dc_elements)) * 0.6
        return min(score, 1.0)

    def validate(self, metadata: Dict[str, Any]) -> Dict[str, Any]:
        meta_lower = {k.lower(): v for k, v in metadata.items()}
        warnings = []
        recommended = ["title", "creator", "subject", "description", "identifier"]
        for rf in recommended:
            if rf not in meta_lower:
                warnings.append(f"Recommended DC element absent: {rf}")

        # Check for unrecognised fields
        known = {f.lower() for f in ALL_FIELDS.keys()}
        unknown = [k for k in meta_lower if k not in known and not k.startswith("@")]
        if unknown:
            warnings.append(f"Unknown fields (not DC/DCTerms): {', '.join(unknown[:5])}")

        hits = sum(1 for f in self._dc_elements if f.lower() in meta_lower)
        score = hits / len(self._dc_elements)
        return {"valid": True, "errors": [], "warnings": warnings, "score": score}

    def generate_example(self) -> Dict[str, Any]:
        from engine.generator import FieldGenerator
        gen = FieldGenerator()
        return gen.generate_for_standard(self)
